# window
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 600

# number_change_image_zombie
NUMBER_CHANGE_IMAGE_ZOMBIE = 0.1
NUMBER_CHANGE_MOVE_ZOMBIE = 0.5
NUMBER_POSITION_CAN_REMOVE_ZOMBIE = 50

# Time
TIME_SET_IMAGE = 90000

# Color
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (25, 200, 25)

# Map
START_Y = 50
LINE_Y = 100
START_X = 230
COL_X = 70

# Zombie
WALK = 'walk'
ATTACK = 'attack'
DIE = 'die'
FREEZE = 'freeze'

ZOMBIE_IMAGE_RECT = 'zombie_image_rect'
ZOMBIE_HEAD = 'ZombieHead'
NORMAL_ZOMBIE = 'Zombie'
CONEHEAD_ZOMBIE = 'ConeheadZombie'
BUCKETHEAD_ZOMBIE = 'BucketheadZombie'
FLAG_ZOMBIE = 'FlagZombie'
NEWSPAPER_ZOMBIE = 'NewspaperZombie'
BOOMDIE = 'BoomDie'

LOSTHEAD_HEALTH = 5
NORMAL_HEALTH = 10
FLAG_HEALTH = 15
CONEHEAD_HEALTH = 20
BUCKETHEAD_HEALTH = 30
NEWSPAPER_HEALTH = 15

ATTACK_INTERVAL = 1000
ZOMBIE_WALK_INTERVAL = 70

ICE_SLOW_TIME = 2000
FREEZE_TIME = 7500

# SUN
SUN_VALUE = 25
SUN_LIVE_TIME = 7000
SUN_CHANGE = 1
